### ISSUE TITLE
Version 0.2 showing non-existent led (scroll lock)

### ISSUE THREAD

**Issue by megadr01d** [damieng/setledsmac#11]
Maybe a regression, version 0.2 is showing scroll lock for my MBP keyboard. Version 0.1 correctly shows only num lock and caps lock.

```
❯ setleds -v

SetLEDs version 0.1 - http://github.com/damieng/setledsmac

 "Apple Internal Keyboard / Trackpad" -num -caps 

❯ setleds -v

SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Apple Internal Keyboard / Trackpad" -num -caps -scroll 
```

**Comment by damieng** [comment]
This is a problem in that the Apple driver returns the led status flag indicating it has a scroll lock on that keyboard when it doesn't.

The reason 0.1 didn't show it is it had a bug where it would not fully evaluate all reported indicators.
