### ISSUE TITLE
Add quiet mode

### ISSUE THREAD

**Issue by megadr01d** [damieng/setledsmac#12]
Add `-q` flag to omit output.

```
❯ setleds ^num

SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Apple Internal Keyboard / Trackpad" +num

❯ _
```

```
❯ setleds -q ^num

❯ _
```

**Comment by damieng** [comment]
I'd accept a PR for this but isn't something I'm likely to do myself given I rarely use my Mac any more.

**Comment by damieng** [comment]
You could also just pipe output to /dev/null

`setleds ^num > /dev/null`

**Comment by megadr01d** [comment]
Yeah, dumb of me, I just realized that shortly after I posted. Simple enough. Thanks, man.
