### ISSUE TITLE
Option to set state for same key sequentially

### ISSUE THREAD

**Issue by megadr01d** [damieng/setledsmac#13]
Currently setting the sate for multiple keys is possible

`setleds -caps +scroll ^num`

However setting the state for the same key is not

`setleds +caps -caps` (to mimic `setleds +caps && setleds -caps`)

**Comment by damieng** [comment]
I'd accept a PR for this but isn't something I'm likely to do myself given I rarely use my Mac any more.

**Comment by megadr01d** [comment]
No big thing, `setleds +caps && setleds -caps` will do the trick. I didn't see the timeline on this project so I thought it was still actively maintained. Cheers, man.
