### ISSUE TITLE
Does this work on Mac OS 13?

### ISSUE THREAD

**Issue by pykler** [damieng/setledsmac#18]
Can't get this to work on Mac OS 13 with the prebuilt binary ... does this api still exist to turn the leds on past OsX?

**Comment by damieng** [comment]
Sorry no idea my macbook is too old for 13.

**Comment by polluks** [comment]
Good news: It works with macOS 14.6, there's no API change, just the security of terminal.
You have to right click and open the icon once. Rosetta 2 does its job, however Xcode makes it native.
