### ISSUE TITLE
IOHIDDeviceSetValue returns kIOReturnNotOpen

### ISSUE THREAD

**Issue by xusoo** [damieng/setledsmac#3]
![captura de pantalla 2016-10-01 a las 12 40 29](https://cloud.githubusercontent.com/assets/5207653/19013550/4e1756dc-87d4-11e6-9a46-ae5c7c1727f8.png)

Like in [this other issue](https://github.com/damieng/setledsmac/issues/2), I also had to comment the lines referring to get the current value to avoid the segmentation fault. But then, `IOHIDDeviceSetValue` returns `0xe00002cd` which according to [this](http://opensource.apple.com/source/xnu/xnu-1504.9.37/iokit/IOKit/IOReturn.h) means `kIOReturnNotOpen`... I also tried running it with root privileges but nothing changed.

My keyboard is a Ducky Shine 5 and I'm using it on a hackintosh Sierra. I think the latter will be the key...

**Comment by jialongl** [comment]
Have you tried locating the executable and running it as root?

If that works, you could `chown root` and `chmod 4755` the executable then you'd be able to use it as a normal user.

**Comment by damieng** [comment]
No response to whether tried as root.
