### ISSUE TITLE
scroll led can't be set

### ISSUE THREAD

**Issue by nicexe** [damieng/setledsmac#4]
I'm on OSX Yosemite (10.10.5) on a legit MacBook Pro, using CODE as my keyboard.
setledsmac can only set the leds for `caps` and `num`.
`scroll` doesn't work and it doesn't even appear when I do `setledsmac -v`

```
$ setleds -v
SetLEDs version 0.1 - http://github.com/damieng/setledsmac
 "USB Keyboard" -num -caps
 "Razer Imperator"
 "Apple Internal Keyboard / Trackpad" -num -caps
$ 
```

**Comment by mryanprice** [comment]
Scroll Lock works for me with [one tiny change](https://github.com/damieng/setledsmac/pull/5)

**Comment by damieng** [comment]
Merged.
