### ISSUE TITLE
Segmentation fault: 11 when setting or reading leds

### ISSUE THREAD

**Issue by nicexe** [damieng/setledsmac#6]
setleds seg-faults when setting or reading leds
Example:
```
$ ./setleds -v
SetLEDs version 0.1 - http://github.com/damieng/setledsmac

Segmentation fault: 11
$ 
```

**Comment by nicexe** [comment]
Oops, pebkac.
running setleds as root made it work

**Comment by damieng** [comment]
Ah, good find.  I'll try and put some detection logic in to gracefully fall back and display that it needs to be run as root!
