### ISSUE TITLE
Add blinking support

### ISSUE THREAD

**Issue by hackruu** [damieng/setledsmac#9]
Hello, thanks for a nice tool. Can you please add feature of blinking?
I want to use scroll lock as indicator. So when look at my keyboard i would see some pattern that would tell me smth is happening.
Please add such option. Proposed parameters are 
- num of blinks
- delay between blinks
or, even better —
binary pattern of 1 and 0 and interval between, for example:
- 1 100 0 100 1 50 0 50 — one fast blink, one slower blink
i can simulate this if using this tool in while cycle, but it consumes resources.

Thanks in advance!

**Comment by damieng** [comment]
Making the LEDs blink would be a different type of program - it would need to continue running as a background task/daemon.  

Really the purpose of this program was to replicate the functionality of the Linux 'setleds' command on macOS.
